# Procesamiento del Vector de entrenamiento

In [1]:
#Importo las librerias pandas, numpy y datetime
import pandas as pd
import numpy as np
import datetime

In [2]:
#Cargo el catálogo declusterizado
df = pd.read_csv("salida.csv", sep=',', decimal='.')

In [3]:
#Ordeno el catálogo por cronología siendo el primer evento el más antigüo y el último el más reciente del catálogo
df['date'] = pd.to_datetime(df[['year', 'month', 'day', 'hour', 'minute']])
df =df.sort_values(by='date',ascending=True)
print(df)

      eventID  Agency  year  month  day  hour  minute  second  timeError  \
1728     1747     NaN  2004     11   19     0      20     0.0        NaN   
1729     1748     NaN  2005      1    2     5      24     0.0        NaN   
1730     1749     NaN  2005      1    8     4       9     0.0        NaN   
1731     1750     NaN  2005      4   24     3       9     0.0        NaN   
1732     1751     NaN  2005     12   23     4      53     0.0        NaN   
...       ...     ...   ...    ...  ...   ...     ...     ...        ...   
1724     1743     NaN  2018      2   19    10      11     0.0        NaN   
1725     1744     NaN  2018      2   25     9      37     0.0        NaN   
1726     1745     NaN  2019      5   10     3      52     0.0        NaN   
1712     1731     NaN  2019      5   11     9      56     0.0        NaN   
1727     1746     NaN  2019     11   27     6      56     0.0        NaN   

      longitude  latitude  SemiMajor90  SemiMinor90  ErrorStrike  depth  \
1728  -73094

# Hallamos el b-value de todo el catálogo

In [4]:
#Cálculamos el b-value para todo el catálogo
magnitud = df.iloc[:,16].tolist()
b_value=[]
for idx, val in enumerate(magnitud,start=0):
    sumatoria=0
    for j in range(0,49):      
        indice = (idx - j)
        sumatoria += (magnitud[indice]-2)
    a=0.4342944819/(0.02*sumatoria)
    b_value.append(a)
print(b_value)
print(len(b_value))

[0.27662068910828036, 0.28274380332031257, 0.2887596289228724, 0.2938392976319351, 0.2974619739041096, 0.303702434895105, 0.311099199068768, 0.3170032714598541, 0.32169961622222226, 0.3270289773343374, 0.3330479155674847, 0.3403561770376176, 0.3496734958937199, 0.3577384529654037, 0.36495334613445385, 0.3731052250000001, 0.38096007184210534, 0.3898514200179534, 0.3955323150273225, 0.40361940697026033, 0.4144031315839696, 0.4241157049804689, 0.4274551987204726, 0.43868129484848495, 0.4477262700000001, 0.4590850760042284, 0.4690005204103672, 0.47935373278145704, 0.4901743588036118, 0.5026556503472223, 0.5157891709026129, 0.5194910070574164, 0.5348454210591135, 0.5388269006203474, 0.5525375087786261, 0.5611039817829457, 0.5684482747382199, 0.5806075961229946, 0.5868844349999999, 0.6031867804166666, 0.6221983981375359, 0.6349334530701755, 0.6620342711890242, 0.7027418800970874, 0.7073200030944626, 0.7311354914141417, 0.8616954005952382, 0.8791386273279355, 0.9565957751101324, 0.94824122685

# Hallamos los primeros 5 valores del vector de entrenamiento

In [5]:
#Calculamos las primeras 5 características del Vector de entrenamiento.
Tv={}
for i in range(0,len(b_value)):
    x1=b_value[i]-b_value[i-4]
    x2=b_value[i-4]-b_value[i-8]
    x3=b_value[i-8]-b_value[i-12]
    x4=b_value[i-12]-b_value[i-16]
    x5=b_value[i-16]-b_value[i-20]
    Tv[i]={x1,x2,x3,x4,x5}
print(len(Tv))
print(Tv)

1736
{0: {-0.015636701133980746, 0.00039281907290633633, 0.0011413224105518704, 0.001948361623293482, 0.00192252128346182}, 1: {0.004349904666466398, 0.0023411806961997073, 0.0011443498015871745, -0.013863491588414878, 0.0015400595460613453}, 2: {0.009650064719787521, -0.0011690085827980035, 0.0023286775497546874, -0.011194233858412395, 0.001150440831940991}, 3: {0.019663488351632064, 0.0007824787430813496, 0.0023224635034010954, -0.01768876188905172, 0.00038347892287232677}, 4: {0.02084128479582925, -0.015636701133980746, 0.00039281907290633633, 0.001948361623293482, 0.00192252128346182}, 5: {0.02095863157479244, 0.0023411806961997073, 0.004349904666466398, -0.013863491588414878, 0.0015400595460613453}, 6: {0.022339570145895604, -0.0011690085827980035, 0.0023286775497546874, 0.009650064719787521, -0.011194233858412395}, 7: {0.02316397382791896, 0.0007824787430813496, -0.01768876188905172, 0.0023224635034010954, 0.019663488351632064}, 8: {0.02423764231811265, 0.02084128479582925, -0.01

In [6]:
#Convertirmos el arreglo Tv en un dataframe para visualizarlo con más facilidad
Training = pd.DataFrame()
Training= pd.DataFrame.from_dict(Tv, orient='index',
                       columns=['x1', 'x2', 'x3', 'x4','x5'])
Training

x1        x2        x3        x4        x5
0    -0.015637  0.000393  0.001141  0.001948  0.001923
1     0.004350  0.002341  0.001144 -0.013863  0.001540
2     0.009650 -0.001169  0.002329 -0.011194  0.001150
3     0.019663  0.000782  0.002322 -0.017689  0.000383
4     0.020841 -0.015637  0.000393  0.001948  0.001923
...        ...       ...       ...       ...       ...
1731  0.000782  0.002280  0.000376  0.002322  0.000383
1732  0.000393  0.001948  0.001141  0.001132  0.001923
1733 -0.013863  0.002341  0.001144  0.001887  0.001540
1734 -0.011194 -0.001169  0.002329  0.001150  0.002274
1735 -0.017689  0.000782  0.002280  0.002322  0.000383

[1736 rows x 5 columns]

# Hallamos x6

In [7]:
#Extraemos la fecha y la magnitud para poder calcular mas fácil la característica x6 del Vector de entrenamiento
data = pd.DataFrame()
data['date'] = df['date']
data['magnitud']=df['magnitude']

In [8]:
#Visualizamos el dataframe generado
df=data.set_index(['date'])
df

magnitud
date                         
2004-11-19 00:20:00       2.6
2005-01-02 05:24:00       1.8
2005-01-08 04:09:00       1.7
2005-04-24 03:09:00       2.4
2005-12-23 04:53:00       1.9
...                       ...
2018-02-19 10:11:00       3.4
2018-02-25 09:37:00       3.6
2019-05-10 03:52:00       7.1
2019-05-11 09:56:00       3.5
2019-11-27 06:56:00       4.8

[1736 rows x 1 columns]

In [9]:
#Calculamos el x6
w=pd.DataFrame()
j=[]
inicial=df.index[548]
final=df.index[548]-datetime.timedelta(days=7)
df[final:inicial]
for i in range(len(data)):
    inicial=df.index[i]
    final=df.index[i]-datetime.timedelta(days=7)
    w=df[final:inicial].max()
    j.append(w)
x6 = np.array(j)
print(len(x6))
print(x6)

1736
[[2.6]
 [1.8]
 [1.8]
 ...
 [7.1]
 [7.1]
 [4.8]]


In [10]:
#Agregamos la lista anterior al vector de entrenamiento
Training['x6']=x6
Training

x1        x2        x3        x4        x5   x6
0    -0.015637  0.000393  0.001141  0.001948  0.001923  2.6
1     0.004350  0.002341  0.001144 -0.013863  0.001540  1.8
2     0.009650 -0.001169  0.002329 -0.011194  0.001150  1.8
3     0.019663  0.000782  0.002322 -0.017689  0.000383  2.4
4     0.020841 -0.015637  0.000393  0.001948  0.001923  1.9
...        ...       ...       ...       ...       ...  ...
1731  0.000782  0.002280  0.000376  0.002322  0.000383  4.2
1732  0.000393  0.001948  0.001141  0.001132  0.001923  3.6
1733 -0.013863  0.002341  0.001144  0.001887  0.001540  7.1
1734 -0.011194 -0.001169  0.002329  0.001150  0.002274  7.1
1735 -0.017689  0.000782  0.002280  0.002322  0.000383  4.8

[1736 rows x 6 columns]

# Hallamos el X7

In [11]:
#Calculamos el x7
w=pd.DataFrame()
j=[]
inicial=df.index[548]
final=df.index[548]+datetime.timedelta(days=7)
df[final:inicial]
for i in range(len(data)):
    inicial=df.index[i]
    final=df.index[i]+datetime.timedelta(days=7)
    w=df[inicial:final].max()
    j.append(w)
x7 = np.array(j)
print(len(x7))
print(x7)

1736
[[2.6]
 [1.8]
 [1.7]
 ...
 [7.1]
 [3.5]
 [4.8]]


In [12]:
#Agregamos la lista anterior al vector de entrenamiento
Training['x7']=x7
Training

x1        x2        x3        x4        x5   x6   x7
0    -0.015637  0.000393  0.001141  0.001948  0.001923  2.6  2.6
1     0.004350  0.002341  0.001144 -0.013863  0.001540  1.8  1.8
2     0.009650 -0.001169  0.002329 -0.011194  0.001150  1.8  1.7
3     0.019663  0.000782  0.002322 -0.017689  0.000383  2.4  2.4
4     0.020841 -0.015637  0.000393  0.001948  0.001923  1.9  1.9
...        ...       ...       ...       ...       ...  ...  ...
1731  0.000782  0.002280  0.000376  0.002322  0.000383  4.2  3.6
1732  0.000393  0.001948  0.001141  0.001132  0.001923  3.6  3.6
1733 -0.013863  0.002341  0.001144  0.001887  0.001540  7.1  7.1
1734 -0.011194 -0.001169  0.002329  0.001150  0.002274  7.1  3.5
1735 -0.017689  0.000782  0.002280  0.002322  0.000383  4.8  4.8

[1736 rows x 7 columns]

# Hallamos el Y

In [13]:
#Calculamos el y
w=pd.DataFrame()
j=[]
inicial=df.index[548]
final=df.index[548]+datetime.timedelta(days=7)
df[final:inicial]
for i in range(len(data)):
    inicial=df.index[i]
    final=df.index[i]+datetime.timedelta(days=7)
    w=df[inicial:final].max()
    j.append(w)
print(len(j))
y=np.array(j)
y

1736


array([[2.6],
       [1.8],
       [1.7],
       ...,
       [7.1],
       [3.5],
       [4.8]])

In [14]:
#Agregamos la lista anterior al vector de entrenamiento
Training['y']=y
Training

x1    float64
x2    float64
x3    float64
x4    float64
x5    float64
x6    float64
x7    float64
y     float64
dtype: object

In [21]:
#Revisamos si tenemos valores vacíos o NaN
print(Training.isnull().any())
print(Training.isnull().sum().sum())

x1    False
x2    False
x3    False
x4    False
x5     True
x6    False
x7    False
y     False
dtype: bool
6


In [22]:
#Rellenamos los valores vacíos con 0
Training = Training.fillna(0)

In [23]:
#Creamos un archivo llamado Tv.csv donde se guarda el Vector de entrenamiento final.
Training = np.around(Training,decimals=6)
Training.to_csv(r'c:\Users\yesid\Documents\Tv.csv', index = False)
Training.shape
Training

x1        x2        x3        x4        x5   x6   x7    y
0    -0.015637  0.000393  0.001141  0.001948  0.001923  2.6  2.6  2.6
1     0.004350  0.002341  0.001144 -0.013863  0.001540  1.8  1.8  1.8
2     0.009650 -0.001169  0.002329 -0.011194  0.001150  1.8  1.7  1.7
3     0.019663  0.000782  0.002322 -0.017689  0.000383  2.4  2.4  2.4
4     0.020841 -0.015637  0.000393  0.001948  0.001923  1.9  1.9  1.9
...        ...       ...       ...       ...       ...  ...  ...  ...
1731  0.000782  0.002280  0.000376  0.002322  0.000383  4.2  3.6  3.6
1732  0.000393  0.001948  0.001141  0.001132  0.001923  3.6  3.6  3.6
1733 -0.013863  0.002341  0.001144  0.001887  0.001540  7.1  7.1  7.1
1734 -0.011194 -0.001169  0.002329  0.001150  0.002274  7.1  3.5  3.5
1735 -0.017689  0.000782  0.002280  0.002322  0.000383  4.8  4.8  4.8

[1736 rows x 8 columns]